manager/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView

from manager.views import (
    index,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    AssignWorkersToTaskView,
    WorkerChangePasswordView,
    SignUpWorkerView,
    AssignTaskToWorkerView,
    WorkerTaskCompletionView,
)
from task_manager.settings.base import *


urlpatterns = [
    path("", index, name="index"),
    path("", ProjectListView.as_view(), name="projects"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path(
        "teams/",
        TeamListView.as_view(),
        name="team-list"
    ),
    path(
        "teams/<int:pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/change_password/",
        WorkerChangePasswordView.as_view(),
        name="worker-change-password"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "workers/<int:pk>/assign_task/",
        AssignTaskToWorkerView.as_view(),
        name="worker-assign-task"
    ),
    path(
        "workers/<int:pk>/task/completion/",
        WorkerTaskCompletionView.as_view(),
        name="worker-task-completion"
    ),
    path(
        "setup_worker/",
        SignUpWorkerView.as_view(),
        name="signup-worker"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/assign_worker/",
        AssignWorkersToTaskView.as_view(),
        name="assign-workers-task"
    ),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico")),
] + static(STATIC_URL, document_root=STATIC_ROOT)


app_name = "manager"

manager/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.db.models import Case, When, Value, IntegerField
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from manager.forms import (
    AssignTaskToWorkerForm,
    AssignWorkersToTaskForm,
    PositionCreateUpdateForm,
    ProjectCreateUpdateForm,
    ProjectSearchForm,
    TagCreateUpdateForm,
    TagSearchForm,
    TaskCreateUpdateForm,
    TaskSearchForm,
    TaskTypeCreateUpdateForm,
    TaskTypeSearchForm,
    TeamCreateUpdateForm,
    TeamSearchForm,
    WorkerCreateForm,
    WorkerPasswordChangeForm,
    WorkerSearchForm,
    WorkerUpdateForm,
    WorkerTaskCompletionForm,
)

from manager.models import (
    Position,
    Project,
    Tag,
    Task,
    TaskType,
    Team,
    Worker,
    TaskAssignment,
)


def index(request: HttpRequest) -> HttpResponse:
    number_of_projects = Project.objects.count()
    number_of_teams = Team.objects.count()
    number_of_employees = Worker.objects.count()
    number_of_positions = Position.objects.count()
    number_of_tasks = Task.objects.count()

    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "number_of_projects": number_of_projects,
        "number_of_teams": number_of_teams,
        "number_of_employees": number_of_employees,
        "number_of_positions": number_of_positions,
        "number_of_tasks": number_of_tasks,
        "num_visits": num_visits,
    }

    return render(
        request,
        "manager/index.html",
        context=context,
    )


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    context_object_name = "projects"
    template_name = "manager/project_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = ProjectSearchForm(
            initial={
                "name": name
            },
        )

        return context

    def get_queryset(self):
        queryset = Project.objects.all()
        form = ProjectSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    context_object_name = "project"
    template_name = "manager/project_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project = self.get_object()
        workers = set()
        for team in project.teams.all():
            workers.update(team.workers.values_list("username", flat=True))
        context["project_teams"] = project.teams.values_list("name", flat=True)
        context["project_tasks"] = project.tasks.values_list("name", flat=True)
        context["project_workers"] = list(workers)

        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectCreateUpdateForm
    template_name = "manager/project_create_update_form.html"
    success_url = reverse_lazy("manager:project-list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectCreateUpdateForm
    template_name = "manager/project_create_update_form.html"
    success_url = reverse_lazy("manager:project-list")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    template_name = "manager/project_delete.html"
    success_url = reverse_lazy("manager:project-list")


class TeamListView(LoginRequiredMixin, generic.ListView):
    model = Team
    context_object_name = "teams"
    template_name = "manager/teams_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(TeamListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = TeamSearchForm(
            initial={
                "name": name
            }
        )

        return context

    def get_queryset(self):
        queryset = Team.objects.all()
        form = TeamSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = Team
    context_object_name = "team"
    template_name = "manager/team_detail.html"

    def get_context_data(self, **kwargs):
        context = super(TeamDetailView, self).get_context_data(**kwargs)
        team = self.get_object()
        context["team_workers"] = team.workers.values_list(
            "username",
            flat=True
        )

        return context


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    form_class = TeamCreateUpdateForm
    template_name = "manager/team_create_update_form.html"
    success_url = reverse_lazy("manager:team-list")


class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    form_class = TeamCreateUpdateForm
    success_url = reverse_lazy("manager:team-list")
    template_name = "manager/team_create_update_form.html"


class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    success_url = reverse_lazy("manager:team-list")
    template_name = "manager/team_delete.html"


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    context_object_name = "positions"
    template_name = "manager/position_list.html"
    paginate_by = 5


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position
    context_object_name = "position"
    template_name = "manager/position_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PositionDetailView, self).get_context_data(**kwargs)
        position = self.get_object()
        context["position_workers"] = position.workers.values_list(
            "username",
            flat=True
        )

        return context


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionCreateUpdateForm
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_create_update_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionCreateUpdateForm
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_create_update_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_delete.html"


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    context_object_name = "workers"
    template_name = "manager/worker_list.html"
    queryset = Worker.objects.select_related("position")
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username")
        context["search_form"] = WorkerSearchForm(
            initial={
                "username": username
            }
        )

        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    context_object_name = "worker"
    template_name = "manager/worker_detail.html"

    def get_context_data(self, **kwargs):
        context = super(WorkerDetailView, self).get_context_data(**kwargs)
        worker = self.get_object()
        unique_projects = {
            project for team in self.object.teams.all()
            for project in team.projects.all()
        }
        context["worker_teams"] = worker.teams.values_list("name", flat=True)
        context["worker_tasks"] = worker.tasks.values_list("name", flat=True)
        context["task_assignments"] = TaskAssignment.objects.filter(
            worker=self.object
        )
        context["unique_projects"] = unique_projects

        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    success_url = reverse_lazy("manager:worker-list")
    template_name = "manager/worker_create_update_form.html"

    def form_valid(self, form):
        worker = form.save(commit=False)
        worker.position = form.cleaned_data["position"]
        worker.save()
        return redirect(self.success_url)


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("manager:worker-list")
    template_name = "manager/worker_create_update_form.html"

    def form_valid(self, form):
        worker = form.save(commit=False)
        worker.position = form.cleaned_data["position"]
        worker.save()

templates/manager/index.html
{% extends "base_2.html" %}

{% block content %}
  <header class="header-2">
      <div
          class="page-header min-vh-65 relative"
          style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')"
      >
        <span class="mask bg-gradient-primary opacity-0"></span>
        <div class="container">
          <div class="row">
            <div class="col-lg-7 text-center mx-auto">
              <h1 class="text-white pt-3 mt-n5">Welcome to Task Manager</h1>
              <p class="lead text-white mt-3">
                Here you can create your own projects,<br>
                teams, tasks, workers, etc.
              </p>
            </div>
          </div>
        </div>
      </div>
    </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">
                    <span id="state1">
                      {{ number_of_projects }}
                    </span>
                  </h1>
                  <h5 class="mt-3">Number of Projects</h5>
                  <p class="text-sm font-weight-normal">
                    Project we're realized or in progress
                  </p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">
                    <span id="state2">
                      {{ number_of_teams }}
                    </span>
                  </h1>
                  <h5 class="mt-3">Number of Teams</h5>
                  <p class="text-sm font-weight-normal">
                    Teams which work with actual projects
                  </p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">
                    <span id="state3">
                      {{ number_of_employees }}
                    </span>
                  </h1>
                  <h5 class="mt-3">Number of Employees</h5>
                  <p class="text-sm font-weight-normal">
                    Our powerful employees which work in strong teams with actual and interesting projects
                  </p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">
                    <span id="state4">
                      {{ number_of_positions }}
                    </span>
                  </h1>
                  <h5 class="mt-3">Number of Positions</h5>
                  <p class="text-sm font-weight-normal">
                    Our needed and actual positions
                  </p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">
                    <span id="state3">
                      {{ number_of_tasks }}
                    </span>
                  </h1>
                  <h5 class="mt-3">Number of Tasks</h5>
                  <p class="text-sm font-weight-normal">
                    Easy and tricky tasks that we are solving every day
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/manager/position_delete.html
{% extends "base.html" %}

{%  block content %}
  <div class="container-fluid text-white">
    <h1>Position Deleting</h1>
    <p><strong>WARNING!</strong> You're going to delete position - {{ position.name }}!</p>
    <p><i>If you're really sure to delete this position, please press "Delete" button below.</i></p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete" class="btn btn-danger">
    </form>
  </div>
{% endblock %}

templates/manager/position_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4 text-white">
      <h1>
        About position "{{ position.name }}"
      </h1>
      <a
          href="{% url 'manager:position-update' pk=position.id %}"
          class="btn btn-info"
      >
        Edit
      </a>
    </div>
    <hr class="text-white-50">
    {% if position.name != "DevOps" %}
      <h4 class="text-white">Our Company {{ position.name }}s:</h4>
      {% if position.workers.all %}
        <ol class="text-white">
          {% for worker in position.workers.all %}
            {% if worker.first_name and worker.last_name %}
              <li>
                <a
                    href="{% url 'manager:worker-detail' pk=worker.id %}"
                    class="text-decoration-none text-white"
                >
                  {{ worker.username }}
                </a>
                ({{ worker.first_name }} {{ worker.last_name }})
              </li>
            {% else %}
              <li>
                {{ worker.username }}
              </li>
            {% endif %}
          {% endfor %}
        </ol>
      {% else %}
        <p class="text-white">
          There are no represented {{ position.name }}s in Company!
        </p>
      {% endif %}
    {% else %}
        <h4>Our Company {{ position.name }}:</h4>
      {% if position.workers.all %}
        <ol>
          {% for worker in position.workers.all %}
            {% if worker.first_name and worker.last_name %}
              <li>
                <a
                    href="{% url 'manager:worker-detail' pk=worker.id %}"
                >
                  {{ worker.username }}
                </a>
                ({{ worker.first_name }} {{ worker.last_name }})
              </li>
            {% else %}
              <li>
                {{ worker.username }}
              </li>
            {% endif %}
          {% endfor %}
        </ol>
      {% else %}
        <p
            class="text-white"
        >
          There are no represented {{ position.name }} in Company!
        </p>
      {% endif %}
    {% endif %}
    <hr class="text-white-50">
    <a
        href="{% url 'manager:position-delete' pk=position.id %}"
        class="btn btn-danger"
    >
      Delete
    </a>
  </div>
{% endblock %}

templates/manager/position_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="text-white">
        List of all actual working positions:
      </h1>
      <a
          href="{% url 'manager:position-create' %}"
          class="btn btn-success"
      >
        Add new Position
      </a>
    </div>
    <hr class="text-white-50">
    {% if positions %}
      <table class="table table-bordered text-dark text-start bg-white">
        <thead>
          <tr>
            <th>
              ID
            </th>
            <th>
              Position name
            </th>
            <th>
              Number of position workers
            </th>
            <th>
              Update
            </th>
            <th>
              Delete
            </th>
          </tr>
        </thead>
        <tbody>
          {% for position in positions  %}
            <tr>
              <td>
                {{ position.id }}
              </td>
              <td>
                <a
                    href="{% url 'manager:position-detail' pk=position.id %}"
                    class="text-decoration-none"
                >
                  {{ position.name }}
                </a>
              </td>
              <td>
                {{ position.workers.count }}
              </td>
              <td>
                <a
                    href="{% url 'manager:position-update' pk=position.id %}"
                    class="btn btn-info"
                >
                  Update
                </a>
              </td>
              <td>
                <a
                    href="{% url 'manager:position-delete' pk=position.id %}"
                    class="btn btn-danger"
                >
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="text-white">There are still no positions created!</p>
    {% endif %}
  </div>
{% endblock %}

templates/manager/project_create_update_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="min-vh-100">
    <h1
      class="text-white"
    >
      {{ object|yesno:"Update,Create" }} Project
    </h1>
    <form action="" method="post" class="text-white">
      {% csrf_token %}
      {{ form|crispy }}
      <input
        type="submit"
        value="{{ object|yesno:'Update,Create' }}"
        class="btn btn-info"
      >
    </form>
  </div>
{% endblock %}

templates/manager/project_createupdate_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Project</h1>
  <form action="{% url 'manager:project-list' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input
        type="submit"
        value="{{ object|yesno:'Update,Create' }}"
        class="btn btn-info"
    >
  </form>
{% endblock %}

templates/manager/team_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid py-2">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="text-white">
        Info about "{{ team.name }}"
      </h1>
      <a
          href="{% url 'manager:team-update' pk=team.id %}"
          class="btn btn-info link-to-page"
      >
        Edit
      </a>
    </div>
    <hr class="text-white-50">
    <h5 class="text-white">Description:</h5>
    <p class="text-white">{{ team.description }}</p>
    <h5 class="text-white">Team Members:</h5>
    {% if team.workers.all %}
      <ul class="list-inline text-white-50">
        {% for worker in team.workers.all %}
          <li>
            <a
                href="{% url 'manager:worker-detail' pk=worker.id %}"
                class="text-decoration-none text-white"
            >
              {{ worker.username }}
            </a>
            {% if worker.position %}
              (
              {% if worker.first_name and worker.last_name %}
                {{ worker.first_name }} {{ worker.last_name }}
              {% endif %}
              {% if worker.position %}
                , {{ worker.position }}
              {% endif %}
              )
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-white">There are no workers assigned to this team.</p>
    {% endif %}
    <hr class="text-white-50">
    <a
      href="{% url 'manager:team-delete' pk=team.id %}"
      class="btn btn-danger link-to-page"
  >
    Delete
  </a>
  </div>
{% endblock %}

templates/manager/teams_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div
        class="d-flex justify-content-between align-items-center mb-4"
    >
      <h1 class="text-white">
        List of all Teams:
      </h1>
      <a
          href="{% url 'manager:team-create' %}"
          class="btn btn-success"
      >
        Create a new Team
      </a>
    </div>
    {% if teams %}
      <form action="" method="get" class="mb-4">
        {{ search_form|crispy }}
        <input
            type="submit"
            value="Search"
            class="btn btn-info mt-2"
        >
      </form>
    {% endif %}
    {% if teams %}
      <table class="table table-bordered text-dark text-start bg-white">
        <thead>
          <tr>
            <th>ID</th>
            <th>Team name</th>
            <th>Number of Workers</th>
          </tr>
        </thead>
        <tbody>
          {% for team in teams %}
            <tr>
              <td>{{ team.id }}</td>
              <td>
                <a
                    href="{% url 'manager:team-detail' pk=team.id %}"
                    class="text-decoration-none"
                >
                  {{ team.name }}
                </a>
              </td>
              <td>
                {{ team.workers.count }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="text-white">There are still no teams created!</p>
    {% endif %}
  </div>
{% endblock %}

templates/manager/worker_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div
        class="d-flex
        justify-content-between
        align-items-center
        mb-4"
    >
      <h1 class="text-white">
        Actual list of Employees:
      </h1>
      <a
          href="{% url 'manager:worker-create' %}"
          class="btn btn-success"
      >
        Add new Worker
      </a>
    </div>
    {% if workers %}
      <form action="" method="get">
        {{ search_form|crispy }}
        <input
            type="submit"
            value="Search"
            class="btn btn-info"
        >
      </form>
    {% endif %}
    <hr>
    <table class="table table-bordered text-dark text-start bg-white">
      <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Position</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for worker in workers %}
          <tr>
            <td>{{ worker.id }}</td>
            <td>
              <a
                  href="{% url 'manager:worker-detail' pk=worker.id %}"
                  class="text-decoration-none"
              >
                {% if user.username == worker.username %}
                  {{ worker.username }} (Me)
                {% else %}
                  {{ worker.username }}
                {% endif %}
              </a>
            </td>
            <td>{{ worker.first_name }}</td>
            <td>{{ worker.last_name }}</td>
            <td>{{ worker.position }}</td>
            <td>
              <a
                  href="{% url 'manager:worker-update' pk=worker.id %}"
                  class="btn btn-info"
              >
                Update
              </a>
            </td>
            <td>
              <a
                  href="{% url 'manager:worker-delete' pk=worker.id %}"
                  class="btn btn-danger"
              >
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}