manager/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView

from manager.views import (
    index,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    AssignWorkersToTaskView,
    WorkerChangePasswordView,
    SignUpWorkerView,
    AssignTaskToWorkerView,
    WorkerTaskCompletionView,
)
from task_manager.settings.base import *


urlpatterns = [
    path("", index, name="index"),
    path("", ProjectListView.as_view(), name="projects"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path(
        "teams/",
        TeamListView.as_view(),
        name="team-list"
    ),
    path(
        "teams/<int:pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/change_password/",
        WorkerChangePasswordView.as_view(),
        name="worker-change-password"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "workers/<int:pk>/assign_task/",
        AssignTaskToWorkerView.as_view(),
        name="worker-assign-task"
    ),
    path(
        "workers/<int:pk>/task/completion/",
        WorkerTaskCompletionView.as_view(),
        name="worker-task-completion"
    ),
    path(
        "setup_worker/",
        SignUpWorkerView.as_view(),
        name="signup-worker"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/assign_worker/",
        AssignWorkersToTaskView.as_view(),
        name="assign-workers-task"
    ),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico")),
] + static(STATIC_URL, document_root=STATIC_ROOT)


app_name = "manager"

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a
                class="navbar-brand font-weight-bolder ms-sm-3"
                href="{% url 'index' %}"
                rel="tooltip"
                data-placement="bottom"
            >
              Task Manager
            </a>
            <div
                class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100"
                id="navigation"
            >
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:project-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Projects
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:team-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Teams
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:worker-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Employees
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:position-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Positions
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:task-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Tasks
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:task-type-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Task Types
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a
                      href="{% url 'manager:tag-list' %}"
                      class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                  >
                    Tags
                  </a>
                </li>

                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a
                        class="nav-link nav-link-icon me-2"
                        href="{% url 'logout' %}"
                    >
                      <p
                          class="d-inline text-sm z-index-1 font-weight-bold"
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title="Sign OUT"
                      >
                        Logout
                      </p>
                    </a>
                  </li>
                {% else %}
                  <li class="nav-item ms-lg-auto">
                    <a
                        href="{% url 'login' %}"
                        class="nav-link nav-link-icon me-2"
                    >
                      <p
                          class="d-inline text-sm z-index-1 font-weight-bold"
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title="Login"
                      >
                        Login
                      </p>
                    </a>
                  </li>
                  <li class="nav-item ms-lg-auto">
                    <a
                        href="{% url 'manager:signup-worker' %}"
                        class="nav-link nav-link-icon me-2"
                    >
                      <p
                          class="d-inline text-sm z-index-1 font-weight-bold"
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title="Sign Up"
                      >
                        Sign Up
                      </p>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
<ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a
          href="?{% query_transform request page=page_obj.previous_page_number %}"
          class="page-link"
      >Prev</a>
    </li>
  {% endif %}

  <li class="page-item active">
    <span class="page-link">{{ page_obj.number }} / {{paginator.num_pages }}</span>
  </li>

  {% if page_obj.has_next %}
    <li>
      <a
          href="?{% query_transform request page=page_obj.next_page_number %}"
          class="page-link"
      >Next</a>
    </li>
  {% endif %}
</ul>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <p class="text-white">
      Hello, <strong class="text-primary">{{ user.username }}</strong>!
    </p>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Logout" class="btn btn-danger">
    </form>
  {% else %}
    <p class="text-white">
      Hello, <strong class="text-primary">Unknown_user</strong>!
    </p>
    <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    <br>
    <a href="{% url 'manager:signup-worker' %}" class="btn btn-info">Sign Up</a>
  {% endif %}
  <hr class="text-white">
  <li class="list-group-item ">
    <a
        href="{% url 'index' %}"
        class="text-decoration-none text-black-50"
    >
      Home
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:project-list' %}"
        class="text-decoration-none text-black-50"
    >
      Projects
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:team-list' %}"
        class="text-decoration-none text-black-50"
    >
      Teams
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:worker-list' %}"
        class="text-decoration-none text-black-50"
    >
      Employees
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:position-list' %}"
        class="text-decoration-none text-black-50"
    >
      Positions
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:task-list' %}"
        class="text-decoration-none text-black-50"
    >
      Tasks
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:task-type-list' %}"
        class="text-decoration-none text-black-50"
    >
      Task types
    </a>
  </li>
  <li class="list-group-item">
    <a
        href="{% url 'manager:tag-list' %}"
        class="text-decoration-none text-black-50"
    >
      Tags
    </a>
  </li>
</ul>